#ifndef CONFIG_HPP_NOUVOCHAP
#define CONFIG_HPP_NOUVOCHAP

#define NOUVOCHAP_MAJOR @NOUVOCHAP_MAJOR@
#define NOUVOCHAP_MINOR @NOUVOCHAP_MINOR@
#define NOUVOCHAP_PATCH @NOUVOCHAP_PATCH@
#define NOUVOCHAP_RELEASE @NOUVOCHAP_RELEASE@

#endif // CONFIG_HPP_NOUVOCHAP
